version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install cmake
            gem update --system
            gem install bundler
            bundle install --path vendor/bundle --with development test
      - run:
          name: Running checks
          command: |
            git config --global user.email "circle@example.com"
            git config --global user.name "Circle CI"
            bundle exec overcommit -s
            bundle exec overcommit -r
  test:
    docker:
      - image: circleci/ruby:2.5.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install cmake
            gem update --system
            gem install bundler
            bundle install --path vendor/bundle --with development test
      - run:
          name: Running tests
          command: |
            bundle exec rspec
      - run:
          name: Check coverage
          command: |
            bundle exec undercover --compare origin/master
