version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem update --system
            gem install bundler
      - ruby/bundle-install
      - run:
          name: bundle-audit check
          command: bundle exec bundle-audit check --update
      - run: 
          name: brakeman check
          command: bundle exec brakeman
      - run: 
          name: rails_best_practices check
          command: bundle exec rails_best_practices .
      - run: 
          name: rails_best_practices check
          command: bundle exec rails_best_practices .
      - run: 
          name: fasterer check
          command: bundle exec fasterer
      - run: 
          name: reek check
          command: bundle exec reek
      - run: 
          name: rubocop check
          command: bundle exec rubocop