version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem update --system
            gem install bundler
      - ruby/bundle-install
      - run:
          name: Running checks
          command: |
            bundle exec bundle-audit check --update
            bundle exec brakeman
            bundle exec rails_best_practices .
            bundle exec fasterer
            bundle exec reek
            bundle exec rubocop


