default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: brind_the_dishes_development

test:
  <<: *default
  database: brind_the_dishes_test

production:
  <<: *default
  database: brind_the_dishes_production
  username: brind_the_dishes
  password: <%= ENV['BRING_THE_DISHES_DATABASE_PASSWORD'] %>
