bundler-audit:
  description: 'bundler-audit'
  command:     'bundle exec bundle-audit'
  required:    true
brakeman:
  description: 'brakeman'
  command:     'bundle exec brakeman'
  required:    true
rails_best_practices:
  description: 'rails_best_practices'
  command:    'bundle exec rails_best_practices .'
  required:   true
fasterer:
  description: 'fasterer'
  command:    'bundle exec fasterer'
  required:   true
reek:
  description: 'reek'
  command:    'bundle exec reek'
  required:   true
rubocop:
  description: 'rubocop'
  command:     'bundle exec rubocop'
  required:    true